### ISSUE TITLE
EC key module which is dependency for target365-sdk is showing compatibility issue is node ver 20.

### ISSUE THREAD

**Issue by Aamer-Rasheed** [Target365/sdk-for-node#11]
I want to use target365-SDK in my project and I have node.js ver 20.0 but I'm having issue in EC key module as its incompatible. Following is the error when I try to install using yarn.

warning target365-sdk > @hapi/joi@15.1.1: Switch to 'npm install joi'
warning target365-sdk > @hapi/joi > @hapi/hoek@8.5.1: This version has been deprecated and is no longer supported or maintained
warning target365-sdk > @hapi/joi > @hapi/topo@3.1.6: This version has been deprecated and is no longer supported or maintained
warning target365-sdk > @hapi/joi > @hapi/topo > @hapi/hoek@8.5.1: This version has been deprecated and is no longer supported or maintained
warning target365-sdk > @hapi/joi > @hapi/address@2.1.4: Moved to 'npm install @sideway/address'
warning target365-sdk > @hapi/joi > @hapi/bourne@1.3.2: This version has been deprecated and is no longer supported or maintained
[2/4] Fetching packages...
error ec-key@0.0.2: The engine "node" is incompatible with this module. Expected version "~6.0.". Got "20.16.0"

**Comment by HansOlavS** [comment]
Hi @Aamer-Rasheed. This issue should be fixed now. Please update to the lastest version and try.
